services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      # expose when debugging
      - "12345:12345"
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # app log (optional)
      # - /opt/home/matthew/SIP_server:/app/logs
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    restart: unless-stopped
